// Code generated by fsetcodegen; DO NOT EDIT.
package fakerpc

import (
	"context"
	"errors"
	"github.com/johnsiilver/fsets"
)

// newServeFsetCompiled returns a compiled pipeline for the fset with required objects.
func newServeFsetCompiled(obj *RPCServer) func(ctx context.Context, so fsets.StateObject[serveSO]) fsets.StateObject[serveSO] {
	return func(ctx context.Context, so fsets.StateObject[serveSO]) fsets.StateObject[serveSO] {
		var err error
		if ctx == nil {
			ctx = context.Background()
		}
		so.SetCtx(ctx)
		if so.Data.req.User == "" {
			err = errors.New("user not authenticated")
			so.SetErr(err)
			return so
		}
		if so.Data.req.User != "admin" {
			err = errors.New("unauthorized user")
			so.SetErr(err)
			return so
		}

		if so.Data.req.Data == "" {
			err = errors.New("no data provided")
			so.SetErr(err)
			return so
		}
		so.Data.resp.Data = "Processed: " + so.Data.req.Data

		return so
	}
}
