// Code generated by fsetcodegen; DO NOT EDIT.
package fakerpc

import (
	"context"
	"github.com/johnsiilver/fsets"
)

// newServeFsetCompiled returns a compiled pipeline for the fset with required objects.
func newServeFsetCompiled(obj *RPCServer) func(ctx context.Context, so fsets.StateObject[serveSO]) fsets.StateObject[serveSO] {
	return func(ctx context.Context, so fsets.StateObject[serveSO]) fsets.StateObject[serveSO] {
		var err error
		if ctx == nil {
			ctx = context.Background()
		}
		so.SetCtx(ctx)
		so, err = obj.handleAuth(so)
		if err != nil || so.GetStop() {
			so.SetErr(err)
			return so
		}
		so, err = obj.handleData(so)
		if err != nil || so.GetStop() {
			so.SetErr(err)
			return so
		}
		return so
	}
}
