// Code generated by fsetcodegen; DO NOT EDIT.
package compiler

import (
	"context"
	"github.com/johnsiilver/fsets"
)

// NewMyFsets2Compiled returns a compiled pipeline for the fset with required objects.
func NewMyFsets2Compiled(obj *Stuff) func(ctx context.Context, so fsets.StateObject[Args]) fsets.StateObject[Args] {
	return func(ctx context.Context, so fsets.StateObject[Args]) fsets.StateObject[Args] {
		var err error
		if ctx == nil {
			ctx = context.Background()
		}
		so.SetCtx(ctx)
		so, err = obj.Fa(so)
		if err != nil || so.GetStop() {
			so.SetErr(err)
			return so
		}
		so, err = obj.Fb(so)
		if err != nil || so.GetStop() {
			so.SetErr(err)
			return so
		}
		so, err = obj.Fc(so)
		if err != nil || so.GetStop() {
			so.SetErr(err)
			return so
		}
		return so
	}
}
